In [1]:
import numpy as np

In [2]:
matrix = np.array([
    [1,1,2],
    [3,5,8],
    [13,21,34]
])

In [3]:
multiply_2 = lambda i: i * 2

In [4]:
vectorized_multiply = np.vectorize(multiply_2)

In [5]:
vectorized_multiply(matrix)

array([[ 2,  2,  4],
       [ 6, 10, 16],
       [26, 42, 68]])

# Finding Maximum and Minimum Values

In [6]:
import numpy as np

In [7]:
matrix = np.array([
    [1,3,5,6,3],
    [4,56,8,4,3],
    [8,5,7,5,4]
])

In [8]:
np.max(matrix)

np.int64(56)

In [9]:
np.max(matrix, axis=0)

array([ 8, 56,  8,  6,  4])

In [10]:
np.max(matrix, axis=1)

array([ 6, 56,  8])

# 1.8 Calculating the Average, Variance, and Standard Deviation

In [11]:
import numpy as np

In [12]:
matrix = np.array([
    [1,1,2],
    [3,5,8],
    [13,21,34]
])

In [13]:
np.mean(matrix)

np.float64(9.777777777777779)

In [14]:
np.var(matrix)

np.float64(112.17283950617283)

In [15]:
np.std(matrix)

np.float64(10.591167995371087)

In [16]:
np.mean(matrix, axis=0)

array([ 5.66666667,  9.        , 14.66666667])

# 1.9 Reshaping Arrays

In [17]:
import numpy as np

In [18]:
matrix = np.array([
    [1,1,2],
    [3,5,8],
    [13,21,34],
    [55, 89, 144]
])

In [19]:
reshaped = np.reshape(matrix, (2,6))

In [20]:
print(reshaped)

[[  1   1   2   3   5   8]
 [ 13  21  34  55  89 144]]


# 1.10 Introduction to Linear Algebra

In [21]:
import numpy as np

In [22]:
A = np.array([
    [5, 3],
    [-6,-4]
])

In [23]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [24]:
print(eigenvalues)

[ 2. -1.]


In [25]:
print(eigenvectors)

[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [26]:
np.linalg.inv(A)

array([[ 2. ,  1.5],
       [-3. , -2.5]])

# Post Lab Exercise
## 1. Write a program to check whether all elements in an array are non zero.

In [27]:
import numpy as np

In [28]:
to_check = np.array([1,0,45,6,6,4,2])

In [29]:
if np.all(to_check) == True:
  print("All elements are non-zero")

## 2. Write a program to create a 2X2 matrix of ones and adding a border around it with zeros.

In [30]:
import numpy as np

In [31]:
the_ones = np.ones((2,2))

In [32]:
np.pad(the_ones, 1, mode="constant", constant_values=0)

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

# 3.Write a program to multiply a randomly generated 4X3 size matrix to randomly generated 3X5 size matrix.

In [33]:
import numpy as np

In [34]:
np.matmul(np.random.rand(4,3), np.random.rand(3,5))

array([[0.7589571 , 1.17285237, 1.0187091 , 1.43035594, 1.05286345],
       [0.73323745, 0.97099565, 0.53443244, 1.13851682, 0.63326117],
       [0.96589236, 1.35793097, 0.71211875, 1.56568345, 0.9104584 ],
       [0.6307608 , 1.11298817, 0.79834737, 1.28877175, 0.9759676 ]])

# 4. Write a program to solve the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2

In [35]:
import numpy as np

In [36]:
A = np.array([
    [1,2],
    [3,5]
])

In [37]:
B = np.array([
    [1],
    [2]
])

In [38]:
np.linalg.solve(A,B)

array([[-1.],
       [ 1.]])